---
title: "Projection Prediction Inference: Data Preprocessing"
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    code_folding: show
    number_sections: no
  html_document:
    toc: yes
    df_print: paged
---

## Data Preprocessing

### load packages
```{r, cache = F}
library(tidyverse)
```

### load data
```{r}
apes1 <- read_csv("../../../data/laac_data_trial_phase1.csv")
apes2 <- read_csv("../../../data/laac_data_task_phase1.csv")
```

### create summed `code` variable
```{r}
fn0 <- function(x, ...) {
  # helper function
  # sum over correct choice variable (code)
  to_return = tibble(cogn = sum(x$code))
  return(to_return)
}

code_sum <- apes1 %>%
  # contains summed code variable [for each task, time point, session and subject]
  group_by(time_point, session, subject, task) %>%
  group_modify(fn0)

apes1_tmp <- apes1 %>%
  # helper for merging
  select(-c(date, trial_session, trial_time_point, code)) %>%
  unique(by = c("time_point", "session", "subject"))

apes1_new <-
  as_tibble(merge(apes1_tmp, code_sum, by = c("time_point", "session", "subject", "task"))) %>%
  mutate(across(c(subject, group, heat, test_day, le_present, dist_present, sex, rearing, observer), as_factor)) %>%
  mutate(observer = fct_relevel(observer, "no")) %>% 
  jtools::center(.,vars = c("sick_severity",
                            "le_mean",
                            "time_outdoors",
                            "age",
                            "time_in_leipzig")) %>%
  group_by(group, time_point) %>%
  mutate(rank_gmc = rank - mean(rank, na.rm = TRUE)) %>%
  ungroup() %>%
  arrange(time_point)
```

### feature engineering
```{r}
grp_size <- tibble(
  # number of apes for each species
  a_chimp = 20,
  b_chimp = 6,
  bonobo = 12,
  gorilla = 6,
  orangutan = 6
)

apes1_new <- apes1_new %>%
  # create rank variable depending on species
  group_by(group, time_point) %>%
  mutate(
    rel_rank = case_when(
      group == "a_chimp" ~ percent_rank(grp_size$a_chimp:1)[rank],
      group == "b_chimp" ~ percent_rank(grp_size$b_chimp:1)[rank],
      group == "bonobo" ~ percent_rank(grp_size$bonobo:1)[rank],
      group == "gorilla" ~ percent_rank(grp_size$gorilla:1)[rank],
      group == "orangutan" ~ percent_rank(grp_size$orangutan:1)[rank]
    )
  ) %>%
  ungroup()

apes1_new <- apes1_new %>%
  # create coding for heat variable
  mutate(heat_mod = case_when(
    sex == "f" & heat == "yes" ~ "_f_fheat",
    sex == "m" & heat == "yes" ~ "_m_fheat",
    sex == "f" & heat == "no" ~ "_f_noheat",
    sex == "m" & heat == "no" ~ "_m_noheat"),
    heat_mod = as_factor(heat_mod)
  ) %>% 
  mutate(heat_mod = fct_relevel(heat_mod, "_f_noheat"))

apes1_new <- apes1_new %>% 
  select(-heat, -heat_mod)

apes1_new <- apes1_new %>% 
  # recode rearing categories: hand -> unknown
  mutate(rearing = fct_recode(rearing, "hand" = "unknown"))
```

### create tibbles for each task
```{r}
t_cau <- filter(apes1_new, task == "causality")
t_inf <- filter(apes1_new, task == "inference")
t_quant <- filter(apes1_new, task == "quantity")
t_gaze <- filter(apes1_new, task == "gaze_following")

t_gaze <- t_gaze %>%
  # create dummy variable indicating if session 1 or 2
  group_by(time_point, session) %>% 
  mutate(tp_mod = cur_group_id()) %>%
  ungroup() %>% 
  mutate(day2 = case_when(session == 1 ~ "no",
                          session == 2 ~ "yes"),
         day2 = factor(day2)) %>%
  select(tp_mod, day2, everything())

t_gaze <- t_gaze %>%
  # remove duplicates created by day2
  group_by(subject) %>%
  filter(!duplicated(tp_mod)) %>%   
  ungroup() 
```

### save data
```{r}
save(t_cau, t_inf, t_quant, t_gaze, file = "tasks_ppi.Rda")
```

