---
title: "Visualizations"
output:
  pdf_document: default
  html_document: default
date: '2022-03-08'
---

```{r setup, include = FALSE}
library("papaja")
library(png)
library(grid)
library(xtable)
library(tidyverse)
library(tidybayes)
library(ggridges)
library(glue)
library(brms)
library(stringr)
library(forcats)
library(ggthemes)
library(ggpubr)
library(reshape)
library(ggExtra)
library(tidyboot)
library(MplusAutomation)
library(kableExtra)
library(knitr)
#library(magick)
#library(pdftools)
library(projpred)
library(bayesplot)
library(loo)
library(directlabels)
library(ggside)
library(cowplot)
library(geomtextpath)

source("../utils/custom_facet.R")

#source("../../utils/custom_facet.R")

cor_func <- function(x) {
  x %>%
    corrr::correlate()%>%
    gather(time_point, cor, -term)%>%
    mutate(cor = replace(cor, duplicated(cor), NA))%>%
    drop_na(cor)
}

library(coda)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```

```{r}
# read in data files
data_task <- read.csv("../data/laac_data_task.csv")%>%
  filter(!grepl("switch", task))%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  mutate(group = recode(group,
    a_chimp = "Chimpanzee group A",
    b_chimp = "Chimpanzee group B",
    bonobo = "Bonobo",
    orangutan = "Orangutan",
    gorilla = "Gorilla"
  ))

data_trial <- read.csv("../data/laac_data_trial.csv") %>%
  filter(!grepl("switch", task))%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  mutate(group = recode(group,
    a_chimp = "Chimpanzee group A",
    b_chimp = "Chimpanzee group B",
    bonobo = "Bonobo",
    orangutan = "Orangutan",
    gorilla = "Gorilla"
  ))
```

```{r}
data_trial%>%
  filter(task == "Inference by exclusion", time_point > 14)%>%
  group_by(group,task, subject, time_point)%>%
  summarise(sum_correct = sum(code))%>%
  ggplot(aes(x = time_point, y = sum_correct, col = group))+
  facet_wrap(group~subject)+
  scale_x_continuous(breaks = c(14:28))+
  geom_point()+
  guides()+
  geom_line()+
  theme_minimal_grid()

ggsave("../visuals/perf_inf_individual.pdf", width = 20, height = 12, scale = 1.1, bg = "white")
```

# Participants

```{r}
participants <- data_trial%>%
  mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species))%>%
  group_by(species)%>%
  mutate(minage = round(min(age),1),
         maxage = round(max(age),1))%>%
  group_by(species, sex, minage,maxage)%>%
  summarise(n = length(unique(subject)))
  
  
 tpn <- data_trial%>%
     mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species))%>%
   group_by(time_point)%>%
   mutate(min_date = min(date))%>%
   group_by(time_point,group,.drop=FALSE)%>%
  summarise(n = length(unique(subject)),
            date = min(min_date))%>%
  group_by(time_point)%>%
  mutate(total_n = sum(n),
         date = as.Date(as.character(min(date)), "%Y%m%d"))%>%
   group_by(group)%>%
   mutate(end = date, 
          start = lag(as.character(end)))%>%
   mutate(start = ifelse(is.na(start),"2020-08-01",start),
          start = as.Date(start, format = "%Y-%m-%d"))%>%
   group_by(time_point)%>%
   mutate(shade = time_point %% 2 == 0)
 
cols <- c(ptol_pal()(5),"black")

ggplot(tpn, aes(x = date, y = n, col = group))+
  geom_rect(aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf, fill= shade), col = NA, alpha =.1)+
  geom_rect(aes(xmin = as.Date("2020-08-01"), xmax = as.Date("2021-03-05"), ymin = 0, ymax = 44),fill = NA, col = "darkgrey")+
  geom_rect(aes(xmin = as.Date("2021-05-10"), xmax = max(date), ymin = 0, ymax = 44),fill = NA, col = "darkgrey")+
  annotate(geom="text", x=as.Date("2020-11-14"), y=46, label="Phase 1", color="black", size=4)+
  annotate(geom="text", x=as.Date("2021-09-14"), y=46, label="Phase 2", color="black", size=4)+
  geom_point(alpha = .6)+
  geom_line(data = tpn%>%filter(time_point > 14), alpha = .6)+
  geom_line(data = tpn%>%filter(time_point < 15), alpha = .6)+
  geom_point(aes(y = total_n), col = "black", alpha = .6)+
  geom_line(data = tpn%>%filter(time_point < 15),aes(y = total_n), col = "black", alpha = .6)+
  geom_line(data = tpn%>%filter(time_point > 14),aes(y = total_n), col = "black", alpha = .6)+
  theme_minimal()+
  ylim(0,48)+
  labs(y = "Sample Size", x = "")+
  scale_color_manual(name = "Species", 
                   limits = c("Chimpanzee group A", "Chimpanzee group B", "Bonobo", "Gorilla", "Orangutan", "total"),
                   labels =c("Chimpanzee gr. A", "Chimpanzee gr. B", "Bonobo", "Gorilla", "Orangutan", "Total"),
                   values = cols)+
  scale_x_date(date_breaks = "1 month",
             date_labels = "%b")+
  scale_fill_manual(values = c("grey", NA))+
  guides(fill = F)
    
```
```{r}
ggsave("../visuals/participants.png", width = 8, height = 3, scale = 1, bg = "white")
```

# Overview performance paper

```{r}
time_plot_1 <- data_task%>%
 filter(!grepl("switch", task))%>%
  mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species),
         group = factor(group))%>%
  drop_na(performance)%>%
  #mutate(time_point = factor(time_point))%>%
  group_by(group, task,time_point, species)%>%
  summarise(mean = mean(performance,na.rm = TRUE))

time_plot_2 <- data_task%>%
filter(!grepl("switch", task))%>%
  mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species),
         group = factor(group))%>%
  drop_na(performance)%>%
  #mutate(time_point = factor(time_point))%>%
  group_by(task, time_point)%>%
  tidyboot_mean(col = performance, na.rm = TRUE)%>%
  mutate(n = n(),
         chance = ifelse(task == "Gaze following" | task == "Delay of gratification", NA,0.5))


time_plot_3 <- data_task%>%
 filter(!grepl("switch", task))%>%
  mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species),
         group = factor(group))%>%
  drop_na(performance)
```

```{r}
time_plot_0 <- data_task%>%
 filter(task == "Inference by exclusion",
        time_point > 14)%>%
  mutate(group = as.character(group), 
         species = ifelse(grepl("chimp",group),"chimpanzee", group), 
         species = factor(species),
         group = factor(group))%>%
  drop_na(performance)

ggplot(time_plot_0, aes(x = time_point, y = performance,  col = group))+
  geom_hline(yintercept = 0.5, lty = 3, col = "black", alpha = .75)+
  geom_point(  alpha = .6, size = 0.75)+
  geom_line(aes(group = subject), alpha = .6, size = 0.5)+
  labs(x = "Time Point", y = "Proportion correct responses")+
  guides(size = F)+
  #geom_smooth(aes(group = subject), se = F)+
  facet_wrap(~subject)+
  theme_few()
  #scale_shape(name = "Switching Phase")+
  scale_color_ptol(name = "Group")+
  theme(legend.position = c(0.8,0.2), legend.direction = "vertical")
```


```{r}
cols1 <- colorblind_pal()(8)[4:8]

ggplot()+
  facet_wrap(~task)+
  geom_vline(xintercept = 14.5)+
  geom_jitter(data = time_plot_3, aes(x = time_point, y = performance,  col = group), alpha = .25, size = 0.3, height = 0.05, width = 0, pch = 1)+
  geom_hline(data = time_plot_2,aes(yintercept = chance), lty = 3, col = "black", alpha = .75)+
  geom_point(data = time_plot_1, aes(x = time_point, y = mean,  col = group), alpha = .6, size = 0.75)+
  geom_line(data = time_plot_1%>%filter(time_point<15), aes(x = time_point, y = mean, col = group, group = group), alpha = .6, size = 0.5)+
  geom_line(data = time_plot_1%>%filter(time_point>14), aes(x = time_point, y = mean, col = group, group = group), alpha = .6, size = 0.5)+
  geom_line(data = time_plot_2%>%filter(time_point<15), aes(x = time_point, y = mean, group = task), size = 0.5, alpha = .5)+
  geom_line(data = time_plot_2%>%filter(time_point>14), aes(x = time_point, y = mean, group = task), size = 0.5, alpha = .5)+
  theme_few()+
  geom_pointrange(data = time_plot_2, aes(x = time_point, y = mean, ymin = ci_lower, ymax = ci_upper),pch = 4, size = 0.5, alpha = .75)+
  scale_x_continuous(breaks = c(1,14,15,28), labels = c(1,14,1,14), minor_breaks = (1:28))+
  labs(x = "Time Point", y = "Proportion correct responses")+
  guides(size = F)+
  #scale_shape(name = "Switching Phase")+
  scale_color_manual(values = cols1,name = "Group")+
  theme(legend.position = c(0.8,0.2), legend.direction = "vertical")#+
  #theme(panel.border = element_rect(color = "black",fill = NA,size = 0.25))
```

```{r}
ggsave("../writing/paper/figures/performance.png", width = 10, height = 4, scale = 1.2, bg = "white")
```

```{r}



```



```{r}
ggplot()+
  facet_wrap(~task)+
  geom_vline(xintercept = 14.5, size = 1)+
  geom_jitter(data = time_plot_3, aes(x = time_point, y = performance,  col = group), alpha = .25, size = 0.3, height = 0.05, width = 0, pch = 1)+
  geom_hline(data = time_plot_2,aes(yintercept = chance), lty = 3, col = "black", alpha = .75)+
  geom_point(data = time_plot_1, aes(x = time_point, y = mean,  col = group), alpha = .6, size = 0.75)+
  geom_line(data = time_plot_1%>%filter(time_point<15), aes(x = time_point, y = mean, col = group, group = group), alpha = .6, size = 0.5)+
  geom_line(data = time_plot_1%>%filter(time_point>14), aes(x = time_point, y = mean, col = group, group = group), alpha = .6, size = 0.5)+
  geom_line(data = time_plot_2%>%filter(time_point<15), aes(x = time_point, y = mean, group = task), size = 0.5, alpha = .5)+
  geom_line(data = time_plot_2%>%filter(time_point>14), aes(x = time_point, y = mean, group = task), size = 0.5, alpha = .5)+
  theme_few()+
  geom_pointrange(data = time_plot_2, aes(x = time_point, y = mean, ymin = ci_lower, ymax = ci_upper),pch = 4, size = 0.5, alpha = .75)+
  scale_x_continuous(breaks = c(1,14,15,28), labels = c(1,14,1,14), minor_breaks = (1:28))+
  labs(x = "Time Point", y = "Proportion correct responses")+
  guides(size = F)+
  #scale_shape(name = "Switching Phase")+
  scale_color_ptol(name = "Group")+
  theme(legend.position = c(0.8,0.2), legend.direction = "vertical")#+
  # theme(panel.border = element_rect(color = "black",fill = NA,size = 0.25))
```

```{r}
ggsave("../visuals/cognition.png", width = 8, height = 4, scale = 1, bg = "white")
```


# Reliability paper

```{r}
cor_data <- bind_rows(
    data_task %>%
    filter(time_point < 15)%>%
  arrange(task)%>%
  drop_na(performance)%>%
  select(subject, task, time_point, performance)%>%
  pivot_wider(values_from = "performance", names_from = "time_point")%>%
  ungroup()%>%
  select(-subject)%>%
  group_by(task)%>%
  group_split(.keep = F)%>%
  setNames(data_task%>%filter(time_point < 15)%>%arrange(task)%>%distinct(task)%>%pull(task))%>%
  purrr::map(cor_func)%>%
  melt()%>%
  mutate(task = factor(L1))%>%
  mutate(phase = "Phase 1"), 
  
data_task %>%
  filter(time_point > 14)%>%
  arrange(task)%>%
  drop_na(performance)%>%
  select(subject, task, time_point, performance)%>%
  pivot_wider(values_from = "performance", names_from = "time_point")%>%
  ungroup()%>%
  select(-subject)%>%
  group_by(task)%>%
  group_split(.keep = F)%>%
  setNames(data_task%>%filter(time_point > 14)%>%arrange(task)%>%distinct(task)%>%pull(task))%>%
  purrr::map(cor_func)%>%
  melt()%>%
  mutate(task = factor(L1))%>%
  mutate(phase = "Phase 2")
  
  )%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))

cor_data_sum <- cor_data%>%
  group_by(phase, task)%>%
  mean_hdci(value)%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))
  
# ggplot(cor_data, aes(x = value, col = task, fill = task))+
#   #geom_histogram(col = "black", fill = "white")+
#   geom_density(alpha = .3)+
#   #xlim(-0.5,1)+
#   #facet_wrap(~task)+
#   labs(x = "Correlation Coefficient", y = "")+
#   theme_minimal()+
#   scale_color_colorblind(name = "Task")+
#   scale_fill_colorblind(name = "Task")


ggplot(data = cor_data, aes(x = value , y = reorder(phase, desc(phase)) ,fill = phase)) +
  geom_vline(xintercept = 0, color = "black", size = .5, lty = 2) +
  geom_density_ridges(rel_min_height = 0.01,col = "black", scale = 1.5,
                      alpha = 0.5) +
  geom_pointinterval(data = cor_data_sum, aes(xmin = .lower, xmax = .upper), size = 1)+
  labs(x = "Re-test correlation",
       y = element_blank()) +
  #geom_text(data = mutate_if(cor_data_sum, is.numeric, round, 2),
   # aes(label = glue("{value} [{.lower}, {.upper}]"), x= Inf), hjust = "inward")+
  theme_minimal()+
  facet_grid(~task)+
  xlim(-0.1,1)+
  #guides(fill = F)+
  scale_fill_colorblind(name= "")+
  theme(panel.border = element_rect(color = "black",fill = NA,size = .25))

cor_data%>%
  mutate(time_span = abs(as.numeric(term) - as.numeric(time_point)))%>%
  ggplot(aes(y = time_span, x = value, col = phase))+
  geom_xsidedensity(aes(x = value, fill = phase),col = "white",alpha = 0.5)+
  geom_point(alpha = .5, size = 0.75)+
  geom_smooth(method = "lm", aes(col = phase),lty = 2, se = T, size = .5)+
  stat_cor(method = "pearson", aes(y = time_span, x = value, col = phase, label = paste(..r.label..)), inherit.aes = F,r.accuracy = 0.01, cor.coef.name = "r", show.legend = FALSE)+
  xlim(-0.1,1)+
  labs(x = "Re-test correlation",
     y = "Distance btw. time points") +
  facet_grid(~task)+
  theme_few()+
  #guides (col = F)+
  scale_colour_colorblind(name= "")+
  scale_fill_colorblind(name= "")+
  ggside(collapse = "x", x.pos = "top", scales = "free_x")+
  theme(#panel.border = element_rect(color = "black",fill = NA,size = .25),
        ggside.panel.border = element_blank(),
        ggside.panel.scale.x = .5,
        axis.title.y = element_text(hjust = 0.2),
        legend.position = c(0.05,0.9),
        legend.background = element_blank())+
  theme_ggside_void()


```

```{r}
ggsave("../writing/paper/figures/reliability.png", width = 10, height = 3.5, scale = 1.25, bg = "white")
```


```{r}
cor_data%>%
  mutate(time_span = abs(as.numeric(term) - as.numeric(time_point)))%>%
  ggplot(aes(y = time_span, x = value, col = phase))+
  geom_xsidedensity(aes(x = value, fill = phase),col = "black",alpha = 0.5)+
  geom_point(alpha = .5, size = 0.75)+
  geom_smooth(method = "lm", aes(col = phase),lty = 2, se = T, size = .5)+
  stat_cor(method = "pearson", aes(y = time_span, x = value, col = phase, label = paste(..r.label..)), inherit.aes = F,r.accuracy = 0.01, cor.coef.name = "r", show.legend = FALSE)+
  xlim(-0.1,1)+
  labs(x = "Re-test correlation",
     y = "Distance btw. time points") +
  facet_grid(~task)+
  theme_few()+
  #guides (col = F)+
  scale_colour_colorblind(name= "")+
  scale_fill_colorblind(name= "")+
  ggside(collapse = "x", x.pos = "top", scales = "free_x")+
  theme(#panel.border = element_rect(color = "black",fill = NA,size = .25),
        ggside.panel.border = element_blank(),
        ggside.panel.scale.x = .5,
        axis.title.y = element_text(hjust = 0.2),
        legend.position = c(0.05,0.9),
        legend.background = element_blank())+
  theme_ggside_void()
```


```{r}
ggsave("../visuals/reliability.png", width = 8, height = 4, scale = 1, bg = "white")
```

# SEM paper

```{r}
# Phase 1: 

#latent state trait models
lstc <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_cau_equSvar.out")
lsti <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_inf_equSvar.out")
lstq <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_quant_equSvar.out")
lstg <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_gaze_equSvar.out")

# latent state trait models with auto regressive component
lstarc <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_cau_equSvar_AR1.out")
lstari <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_inf_equSvar_AR1.out")
lstarq <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_quant_equSvar_AR1.out")
lstarg <- readModels("../models and documentation Jana/Application/one task models/test_apes_data_LST_gaze_equSvar_AR1.out")

# Phase 2: 

# latent state trait models
lstc2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_cau_equSvar.out")
lsti2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_inf_equSvar.out")
lstq2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_quant_equSvar.out")
lstg2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_gaze_equSvar.out")
lstd2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_delay_equSvar.out")

lsti2p2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_inf_equSvar_2phases.out")



# latent state trait models with auto regressive component
#lstarc2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_cau_equSvar_AR1.out")
#lstari2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_inf_equSvar_AR1.out")
#lstarq2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_quant_equSvar_AR1.out")
#lstarg2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_gaze_equSvar_AR1.out")
#lstard2 <- readModels("../models and documentation Jana/Application/Testphase 2/one construct models/test_apes_data_LST_delay_equSvar_AR1.out")

# Relations between tasks
## Phase 1
lstcg <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_cau_gaze.out")
lstci <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_cau_inf.out")
lstcq <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_cau_quant_indspec.out")
lstig <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_inf_gaze.out")
lstiq <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_inf_quant.out")
lstqg <- readModels("../models and documentation Jana/Application/two tasks models/test_apes_data_LST_quant_gaze.out")

## Phase 2
lstcg2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_cau_gaze.out")
lstci2p1 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_cau_inf_phase1.out")
lstci2p2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_cau_inf_phase2.out")
lstcq2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_cau_quant_indspec.out")
lstcd2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_cau_delay.out")

lstig2p1 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_gaze_phase1.out")
lstig2p2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_gaze_phase2.out")
lstiq2p1 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_quant_phase1.out")
lstiq2p2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_quant_phase2.out")
lstid2p1 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_delay_phase1.out")
lstid2p2<- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_inf_delay_phase2.out")

lstqg2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_quant_gaze.out")
lstqd2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_quant_delay.out")

lstgd2 <- readModels("../models and documentation Jana/Application/Testphase 2/two construct models/test_apes_data_LST_gaze_delay.out")
```

```{r}
lst <- bind_rows(
  lstc$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 1"),
  lsti$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 1"),
  lstq$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 1"),
  lstg$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 1"),
  
  lstc2$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 2"),
  #lsti2$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 2"),
  lstq2$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 2"),
  lstg2$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 2"),
  lstd2$parameters$unstandardized%>%mutate(task = "delay_of_gratification", phase = "Phase 2")
  )%>%
  filter(paramHeader== "New.Additional.Parameters",
         !grepl("DIF",param))%>%
  mutate(param = recode(param, CON1 = "Consistency", OCC1 = "Occasion specificity", REL1 = "Reliability"))%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(part = "Part 1")%>%
  bind_rows(lsti2p2$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 2")%>%
  filter(paramHeader== "New.Additional.Parameters",
         !grepl("DIF",param))%>%
  mutate(part = ifelse(grepl("1", param), "Part 1", "Part 2"),
         param = recode(param, CON1 = "Consistency", OCC1 = "Occasion specificity", REL1 = "Reliability",CON2 = "Consistency", OCC2 = "Occasion specificity", REL2 = "Reliability"),
         task = "Inference by exclusion"))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))


plstmpar <- ggplot(lst,aes(x = param, y = est, col = phase, pch = part))+
    geom_pointrange(aes(ymin = lower_2.5ci, ymax = upper_2.5ci), position = position_dodge(width = .7))+
  theme_few()+
  ylim(0,1)+
  facet_wrap(~task)+
  labs(x = "", y = "LST model estimate")+
  scale_color_colorblind(name = "")+
  scale_shape(name = "", guide = F)+
  scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  theme(#legend.text=element_text(size=7), legend.key.size = unit(0.4,"cm"),
    legend.position = c(0.8,0.2), legend.box = "vertical", legend.spacing.x = unit(0, 'cm'), legend.spacing.y = unit(0, 'cm'))
```

```{r}
lstar <- bind_rows(
  lstarc$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 1")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstari$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 1")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstarq$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 1")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstarg$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 1")%>%filter(paramHeader== "New.Additional.Parameters"),
  
  lstarc$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "causality", phase = "Phase 1"),
  lstari$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "inference", phase = "Phase 1"),
  lstarq$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "quantity", phase = "Phase 1"),
  lstarg$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "gaze_following", phase = "Phase 1"),
  
  lstarc2$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 2")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstari2$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 2")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstarq2$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 2")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstarg2$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 2")%>%filter(paramHeader== "New.Additional.Parameters"),
  lstard2$parameters$unstandardized%>%mutate(task = "delay_of_gratification", phase = "Phase 2")%>%filter(paramHeader== "New.Additional.Parameters"),
  
  lstarc2$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "causality", phase = "Phase 2"),
  lstari2$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "inference", phase = "Phase 2"),
  lstarq2$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "quantity", phase = "Phase 2"),
  lstarg2$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "gaze_following", phase = "Phase 2"),
  lstard2$parameters$r2%>%filter(grepl("P",param))%>%mutate(param = str_replace(param,"P1","REL"))%>%filter(param == "REL2"|param == "REL3" |param == "REL14")%>%mutate(task = "delay_of_gratification", phase = "Phase 2")
  )%>%
  filter(!grepl("DIF",param), 
         param != "CON1")%>%
  separate(param, 
           into = c("param", "time_point"), 
           sep = "(?<=[A-Za-z])(?=[0-9])"
           )%>%
  filter(time_point == "14")%>%
  mutate(time_point = as.numeric(time_point),
         param = recode(param, CON = "Consistency", OSP = "Occasion specificity", REL = "Reliability", PRED = "Predictability"))%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))


plstarmpar <- ggplot(lstar,aes(x = param, y = est, col = phase, pch = phase))+
    geom_pointrange(aes(ymin = lower_2.5ci, ymax = upper_2.5ci), position = position_dodge(width = .7))+
  theme_few()+
  ylim(0,1)+
  facet_wrap(~task)+
  labs(x = "", y = "Model estimate")+
  scale_color_colorblind(name = "")+
  scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  scale_shape(name = "")+
  #theme(legend.position = "bottom", legend.box = "vertical")+
  theme(#legend.text=element_text(size=7), legend.key.size = unit(0.4,"cm"),
    legend.position = c(0.8,0.2), legend.box = "vertical", legend.spacing.x = unit(0, 'cm'), legend.spacing.y = unit(0, 'cm'))
```

```{r}
lstar_beta <- bind_rows(
  lstarc$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 1")%>%filter(paramHeader== "S14.ON"),
  lstari$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 1")%>%filter(paramHeader== "S14.ON"),
  lstarq$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 1")%>%filter(paramHeader== "S14.ON"),
  lstarg$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 1")%>%filter(paramHeader== "S14.ON"),

  lstarc2$parameters$unstandardized%>%mutate(task = "causality", phase = "Phase 2")%>%filter(paramHeader== "S14.ON"),
  lstari2$parameters$unstandardized%>%mutate(task = "inference", phase = "Phase 2")%>%filter(paramHeader== "S14.ON"),
  lstarq2$parameters$unstandardized%>%mutate(task = "quantity", phase = "Phase 2")%>%filter(paramHeader== "S14.ON"),
  lstarg2$parameters$unstandardized%>%mutate(task = "gaze_following", phase = "Phase 2")%>%filter(paramHeader== "S14.ON"),
  lstard2$parameters$unstandardized%>%mutate(task = "delay_of_gratification", phase = "Phase 2")%>%filter(paramHeader== "S14.ON")
  )%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))

ggplot(lstar_beta,aes(x = task, y = est, col = phase))+
    geom_pointrange(aes(ymin = lower_2.5ci, ymax = upper_2.5ci), position = position_dodge(width = .7))+
  geom_hline(yintercept = 0,lty = 3, alpha = .75)+
  theme_few()+
  ylim(-1,1.1)+
  #facet_wrap(~task)+
  labs(x = "", y = "LST model estimate")+
  scale_color_colorblind(name = "")+
  scale_shape(name = "")+
  scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  #theme(legend.position = "bottom", legend.box = "vertical")+
  theme(#legend.text=element_text(size=7), legend.key.size = unit(0.4,"cm"),
    legend.position = c(0.15,0.1), legend.direction = "horizontal", legend.spacing.x = unit(0, 'cm'), legend.spacing.y = unit(0, 'cm'))
```


```{r}
lstmcor <- bind_rows(
  bind_rows(
lstcg2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstci2p1$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstci2p2$parameters$stdyx.standardized%>%mutate(part = "Part 2"),
lstcq2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstcd2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstig2p1$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstig2p2$parameters$stdyx.standardized%>%mutate(part = "Part 2"),
lstiq2p1$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstiq2p2$parameters$stdyx.standardized%>%mutate(part = "Part 2"),
lstid2p1$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstid2p2$parameters$stdyx.standardized%>%mutate(part = "Part 2"),
lstqg2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstqd2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstgd2$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
)%>%mutate(phase = "Phase 2"),

bind_rows(
lstcg$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstci$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstcq$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstig$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstiq$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
lstqg$parameters$stdyx.standardized%>%mutate(part = "Part 1"),
)%>%mutate(phase = "Phase 1")
)%>%
  filter(grepl(".WITH", paramHeader))%>%
  mutate(paramHeader = str_replace(paramHeader, "\\.WITH",""),
         type = ifelse(grepl("S",paramHeader),"State residual","Trait"),
         task1 = str_remove_all(paramHeader,"[ST]"),
         task2 = str_remove_all(param,"[ST]"))%>%
  filter(!grepl("1", task1),!grepl("2", task1))%>%
  mutate(task1 = recode(task1, G = "Gaze following", I = "Inference by exclusion", C = "Causal inference", Q = "Quantity discrimination", D = "Delay of grat."),
         task2 = recode(task2, G = "Gaze following", I = "Inference by exclusion", C = "Causal inference", Q = "Quantity discrimination", D = "Delay of grat."),
         )%>%
  filter(type == "Trait")

lstlabel <- lstmcor%>%
  mutate(label = paste0(round(est,2)," \n [", round(lower_2.5ci,2)," ; ", round(upper_2.5ci,2),"]"))%>%
  select(task1,task2,phase,part, label)%>%
  pivot_wider(names_from = part, values_from = label)%>%
  mutate(label = ifelse(phase == "Phase 2" & !is.na(`Part 2`), paste0(`Part 1`,"\n",`Part 2`),`Part 1`))

plstmcor <- lstmcor%>%
  left_join(lstlabel)

pmtm <- plstmcor%>%
  ggplot(aes(y = task1, x = task2, label = label))+
    geom_tile(color = "white", aes(fill = est))+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "#FFE066", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation")+
  facet_grid(~phase)+
  geom_text(size = 2.5, fontface = ifelse(plstmcor$sig == T, 2, 1))+
  theme_few()+
  scale_x_discrete(guide = guide_axis(n.dodge = 2),limits = c("Causal inference", "Quantity discrimination","Gaze following", "Delay of grat."))+
  scale_y_discrete(limits = c( "Inference by exclusion","Delay of grat.","Gaze following", "Quantity discrimination"))+
  theme(legend.text=element_text(size=7),legend.key.size = unit(0.5,"cm"), 
        legend.position = c(0.92,0.75), 
        legend.direction = "vertical", legend.title = element_blank())
```


```{r}
ggarrange(plstmpar, pmtm, widths = c(1,1))
```


```{r}
ggsave("../writing/paper/figures/lstm.png", width = 10, height = 3, scale = 1.5, bg = "white")
```

```{r}
ggsave("../visuals/structure.png", width = 16, height = 4, scale = 1, bg = "white")
```

# PPI 

```{r}
qvarselp <- readRDS("../writing/supplement/saves/cvs_quant_summary.rds")
cvarselp <- readRDS("../writing/supplement/saves/cvs_cau_summary.rds")
ivarselp <- readRDS("../writing/supplement/saves/cvs_inf_summary.rds")
gvarselp <- readRDS("../writing/supplement/saves/cvs_gaze_summary.rds")

qvarselp_p2 <- readRDS("../writing/supplement/saves/cvs_quant_summary_p2.rds")
cvarselp_p2 <- readRDS("../writing/supplement/saves/cvs_cau_summary_p2.rds")
ivarselp_p2 <- readRDS("../writing/supplement/saves/cvs_inf_summary_p2.rds")
gvarselp_p2 <- readRDS("../writing/supplement/saves/cvs_gaze_summary_p2.rds")
dgvarselp_p2 <- readRDS("../writing/supplement/saves/cvs_grat_summary_p2.rds")


ro <- bind_rows(
  qvarselp%>%mutate(task = "quantity")%>%mutate(phase = "Phase 1"),
  cvarselp%>%mutate(task = "causality")%>%mutate(phase = "Phase 1"),
  ivarselp%>%mutate(task = "inference")%>%mutate(phase = "Phase 1"),
  gvarselp%>%mutate(task = "gaze_following")%>%mutate(phase = "Phase 1"),
  
  qvarselp_p2%>%mutate(task = "quantity")%>%mutate(phase = "Phase 2"),
  cvarselp_p2%>%mutate(task = "causality")%>%mutate(phase = "Phase 2"),
  ivarselp_p2%>%mutate(task = "inference")%>%mutate(phase = "Phase 2"),
  gvarselp_p2%>%mutate(task = "gaze_following")%>%mutate(phase = "Phase 2"),
  dgvarselp_p2%>%mutate(task = "delay_of_gratification")%>%mutate(phase = "Phase 2"),
)%>%
  filter(stat == "elpd", 
         solution_terms != "none",
         solution_terms != "day2",
         solution_terms != "(1 | subject)",
         solution_terms != "(time_point | subject)",
         solution_terms != "time_point")%>%
  select(size, solution_terms, task,phase, select)%>%
  group_by(solution_terms)%>%
  mutate(sum = sum(size))%>%
  mutate(task = recode(task,
    gaze_following = "Gaze following",
    causality = "Causal inference",
    inference = "Inference by exclusion",
    delay_of_gratification = "Delay of gratification",
    quantity = "Quantity discrimination",
    switching = "Strategy switching"
  ))%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification"),labels = c("Gaze \nfollowing", "Causal \ninference","Inference \nby exclusion" ,"Quantity \ndiscrimination", "Delay of \ngratification")))%>%
  mutate(type = ifelse(
    solution_terms == "time_in_leipzig" | solution_terms == "rearing" | solution_terms == "group" | solution_terms == "sex"| solution_terms == "age", "Stable characteristic", ifelse(
      solution_terms == "rel_rank" | solution_terms == "sick_severity" | solution_terms == "sociality" ,"Variable characteristic", ifelse(
        solution_terms == "time_outdoors" | solution_terms == "dist_mean" | solution_terms == "le_mean", "Group life", "Testing arrangement"
      )
    )
  ))%>%
  mutate(solution_terms = recode(solution_terms,
    time_in_leipzig = "Time spent in research",
    rearing = "Rearing history",
    group = "Group",
    observer_mod = "Observer present",
    observer = "Observer present",
    sex = "Sex",
    rel_rank = "Rank",
    age = "Age",
    sick_severity = "Sickness severity",
    test_tp = "Study participation (day)",
    test_day = "Study participation (time point)",
    time_outdoors = "Time spent outdoors",
    dist_mean = "Disturbance",
    le_mean = "Life event",
    sociality = "Sociality"
  ))

cols2 <- c("#332288", "#CC6677","#117733","#DDCC77")

p1 <- ggplot(ro,aes(x = fct_reorder(solution_terms,sum), y = size, lty = phase, col = type ))+
  #geom_line(aes(group = task))+
  geom_line(aes(group = phase), alpha = .5, col = "black")+
  geom_point(aes(pch = select), size = 2, stroke = 1)+
  theme_minimal()+
  facet_grid(task~.)+
  labs(x = "", y = "Rank based on PPI model")+
  scale_color_manual(values = cols2, name = "")+
  scale_linetype(name = "")+
  scale_shape_manual(name = "", values =  c(1,19), labels = c("Irrelevant", "Relevant"))+
  scale_y_reverse(breaks = c(15,10,5,1), limits = c(16,0))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.box = "horizontal",
        legend.direction = "vertical",
        legend.position = "top", 
        legend.spacing.y = unit(0, 'cm'),
        #legend.spacing.x = unit(0, 'cm'),
        panel.border  = element_rect(colour = "black",fill = NA)
        )
```




```{r}
proj_samples <- bind_rows(
  readRDS("../writing/supplement/saves/proj_cvs_gaze.rds")%>%mutate(task = "Gaze following", phase = "Phase 1"),
  readRDS("../writing/supplement/saves/proj_cvs_cau.rds")%>%mutate(task = "Causal inference", phase = "Phase 1"),
  readRDS("../writing/supplement/saves/proj_cvs_inf.rds")%>%mutate(task = "Inference by exclusion", phase = "Phase 1"),
  readRDS("../writing/supplement/saves/proj_cvs_quant.rds")%>%mutate(task = "Quantity discrimination", phase = "Phase 1"),
  
  readRDS("../writing/supplement/saves/proj_cvs_gaze_p2.rds")%>%mutate(task = "Gaze following", phase = "Phase 2"),
  readRDS("../writing/supplement/saves/proj_cvs_cau_p2.rds")%>%mutate(task = "Causal inference", phase = "Phase 2"),
  readRDS("../writing/supplement/saves/proj_cvs_inf_p2.rds")%>%mutate(task = "Inference by exclusion", phase = "Phase 2"),
  readRDS("../writing/supplement/saves/proj_cvs_quant_p2.rds")%>%mutate(task = "Quantity discrimination", phase = "Phase 2"),
    readRDS("../writing/supplement/saves/proj_cvs_grat_p2.rds")%>%mutate(task = "Delay of gratification", phase = "Phase 2"),
)%>%
  filter(pred != "time_point",
         !grepl("Intercept", pred))%>%
  mutate(pred = recode(pred,
    time_in_leipzig = "Time spent in research",
    rearing = "Rearing history",
    group = "Group",
    observer = "Observer present",
    observer_mod = "Observer present",
    sex = "Sex",
    rel_rank = "Rank",
    rank = "Rank",
    age = "Age",
    sick_severity = "Sickness severity",
    test_tp = "Study participation (day)",
    test_day = "Study participation (time point)",
    time_outdoors = "Time spent outdoors",
    dist_mean = "Disturbance",
    le_mean = "Life event",
    sociality = "Sociality",
    a_chimp = "Chimpanzee group A",
    b_chimp = "Chimpanzee group B",
    bonobo = "Bonobo",
    orangutan = "Orangutan",
    gorilla = "Gorilla",
    sexf = "Sex (female)",
    rearingmother = "Rearing (mother-reared)",
    observer_modyes = "Observer present",
  ))%>%
  mutate(factor = ifelse(factor == "group", "Group", "    "),
         factor = factor(factor, levels = c("Group", "    ")))


proj_samples_sum <- proj_samples%>%
  group_by(phase,task,factor, pred)%>%
  summarise(mean = mean(value),
            lci = hdi_lower(value),
            uci = hdi_upper(value))

 

p2f <- proj_samples_sum%>%
  ungroup()%>%
  add_row(task = "Delay of gratification", factor = "Group", pred = "Gorilla")%>%
  mutate(task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification"),labels = c("Gaze \nfollowing", "Causal \ninference","Inference \nby exclusion" ,"Quantity \ndiscrimination", "Delay of \ngratification")))%>%
  # mutate(factor= ifelse(pred == "Time spent in research","",factor),
  #        factor= ifelse(pred == "Age","",factor),
  #        factor= ifelse(pred == "Sickness severity","  ",factor),
  #        factor= ifelse(pred == "Time spent outdoors","  ",factor),
  #        factor= factor(factor, levels = c("Group","    ")))%>%
  ungroup()%>%
  filter(pred != "Bonobo")%>%
  mutate(pred2 = recode(pred,
                        `Chimpanzee group A` = 1,
                        `Chimpanzee group B` = 2,
                        Gorilla = 3,
                        Orangutan = 4,
                        `Time spent in research` = 5,
                        Age = 6,
                        `Observer present` = 7,
                        `Rearing (mother-reared)` = 8,
                        `Sickness severity` = 9,
                        `Time spent outdoors` = 10,
                        `Sex (female)` = 11,
                        Sociality = 12, 
                        Rank = 13,
                        `Study participation (day)` = 14))

p2 <- ggplot(p2f,aes(x = pred2, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), pch = 4, size = 0.25, position = position_dodge(width = .5))+
  facet_grid(task~factor, scales = "free", space = "free_x", switch = "x", margins = FALSE,shrink = TRUE)+
  labs(y = "Model estimate", x = "")+
  theme_minimal()+
  scale_color_colorblind(name = "")+
  scale_x_continuous(breaks = c(5:14), labels = c("Time spent in research","                           Age","       Observer present","       Rearing (mother-reared)", "       Sickness severity","     Time spent outdoors","                Sex (female)", "               Sociality","                   Rank","Study participation (day)"),
                     sec.axis = sec_axis(~ .,breaks = c(1:4), labels = c("Chimpanzee group A","Chimpanzee group B", "Gorilla","Orangutan")))+
  theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1, vjust = 1.2),
                legend.direction = "horizontal",
        legend.position = c(0.65, 1.1), 
        legend.spacing.y = unit(0, 'cm'),
        legend.background = element_blank(),
        panel.border  = element_rect(colour = "black",fill = NA),
        axis.text.x.top = element_text(angle = 45, hjust = 0),
        panel.grid.minor = element_blank())

```

```{r}
p2group <- p2f%>%
  filter(factor == "Group")%>%
  ggplot(aes(x = pred2, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), pch = 1, size = 0.25, position = position_dodge(width = .5))+
  #facet_grid(task~factor, scales = "free", space = "free_x", switch = "x", margins = FALSE,shrink = TRUE)+
  facet_wrap_custom(task~., scales = "free_y", ncol = 1, scale_overrides = list(
    scale_override(1, scale_y_continuous(limits = c(-4, 4))),
    scale_override(2, scale_y_continuous(limits = c(-3, 3))),
    scale_override(3, scale_y_continuous(limits = c(-25, 25))),
    scale_override(4, scale_y_continuous(limits = c(-5, 4))),
    scale_override(5, scale_y_continuous(limits = c(1, 1), breaks = c(0,2)))
  ))+
  labs(y = "Model estimate", x = "Group")+
  theme_minimal()+
  scale_color_colorblind(name = "", guide = "none")+
  scale_x_continuous(breaks = c(5:14), labels = c("Time spent in research","                           Age","       Observer present","       Rearing (mother-reared)", "       Sickness severity","     Time spent outdoors","                Sex (female)", "               Sociality","                   Rank","Study participation (day)"),
                     sec.axis = sec_axis(~ .,breaks = c(1:4), labels = c("Chimpanzee group A","Chimpanzee group B", "Gorilla","Orangutan")))+
  theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1, vjust = 1.2),
                legend.direction = "horizontal",
        #legend.position = c(0.5, 0.1),
        legend.spacing.y = unit(0, 'cm'),
        legend.background = element_blank(),
        panel.border  = element_rect(colour = "black",fill = NA),
        axis.text.x.top = element_text(angle = 45, hjust = 0),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(color = "grey20", size = 9),
  strip.text.x = element_blank())

p2other <- p2f%>%
  filter(factor != "Group")%>%
  ggplot(aes(x = pred2, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), pch = 1, size = 0.25, position = position_dodge(width = .5))+
  facet_grid(task~factor, scales = "free", space = "free_x", switch = "x", margins = FALSE,shrink = TRUE)+
  labs(y = "", x = "")+
  theme_minimal()+
  scale_color_colorblind(name = "")+
  scale_x_continuous(breaks = c(5:14), labels = c("Time spent in research","                     Age","    Observer present"," Rearing (mother-reared)", " Sickness severity"," Time spent outdoors","            Sex (female)", "          Sociality","              Rank","Study participation (day)"),
                     sec.axis = sec_axis(~ .,breaks = c(1:4), labels = c("Chimpanzee group A","Chimpanzee group B", "Gorilla","Orangutan")))+
  theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1, vjust = 1.2),
                legend.direction = "horizontal",
        legend.position = c(0.65, 1.1), 
        legend.spacing.y = unit(0, 'cm'),
        legend.background = element_blank(),
        panel.border  = element_rect(colour = "black",fill = NA),
        axis.text.x.top = element_text(angle = 45, hjust = 0),
        panel.grid.minor = element_blank())
```


```{r}
proj_samples%>%
  mutate(fill = ifelse(value > 0, TRUE, FALSE),
         task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  filter(factor == "Group")%>%
  ggplot(aes(x = value, y = phase))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_density_ridges_gradient(aes(fill = stat(x>0)), rel_min_height = 0.01, scale = 1.5, bandwidth = 0.5, col = "white", alpha = .5)+
  stat_pointinterval(.width = .95, size = 1, shape = 1)+
  facet_grid(pred~task, scales = "free_x")+
  scale_fill_manual(values = c("grey", "#85AD00"), guide = "none")+
  theme_minimal()+
  labs(y = "", x = "Model estimate")+
  scale_y_discrete(limits=rev)+
  theme(panel.border  = element_rect(colour = "black",fill = NA))

grouproj <- proj_samples%>%
  add_row(task = "Delay of gratification", factor = "Group", pred = "Gorilla")%>%
  mutate(fill = ifelse(value > 0, TRUE, FALSE),
         task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  filter(factor == "Group")%>%
  ggplot(aes(x = value, y = pred, fill = phase))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_density_ridges(rel_min_height = 0.01, scale = 1.25, bandwidth = 0.15, col = "white", alpha = .5)+
  stat_pointinterval(.width = .95, size = 1, shape = 1)+
  facet_wrap_custom(task~., scales = "free_x", nrow = 1, scale_overrides = list(
    scale_override(1, scale_x_continuous(limits = c(-4, 4))),
    scale_override(2, scale_x_continuous(limits = c(-3, 3))),
    scale_override(3, scale_x_continuous(limits = c(-25, 25))),
    scale_override(4, scale_x_continuous(limits = c(-5, 4))),
    scale_override(5, scale_x_continuous(limits = c(1, 1), breaks = c(0,2)))
  ))+
  scale_y_discrete(labels = c("     Chimpanzee group A","Chimpanzee group B", "Gorilla","Orangutan"))+
  scale_fill_colorblind(name = "Phase")+
  theme_minimal()+
  labs(y = "", x = "Model estimate")+
  scale_y_discrete(limits=rev)+
  theme(panel.border  = element_rect(colour = "black",fill = NA),
        legend.position = c(0.9, 0.5))


otherproj <- proj_samples%>%
  mutate(fill = ifelse(value > 0, TRUE, FALSE))%>%
  filter(factor != "Group")%>%
  mutate(pred = factor(pred, levels = c("Time spent in research","Age", "Observer present", "Rearing (mother-reared)", "Sickness severity", "Time spent outdoors", "Sex (female)", "Sociality", "Rank", "Study participation (day)")),
         task = factor(task, levels = c("Gaze following", "Causal inference","Inference by exclusion" ,"Quantity discrimination", "Delay of gratification")))%>%
  ggplot(aes(x = value, y = pred, fill = phase))+
    facet_wrap_custom(task~., scales = "free_x", nrow = 1, scale_overrides = list(
    scale_override(1, scale_x_continuous(limits = c(-0.5, 0.5))),
    scale_override(2, scale_x_continuous(limits = c(-0.3, 0.3))),
    scale_override(3, scale_x_continuous(limits = c(-0.5, 4))),
    scale_override(4, scale_x_continuous(limits = c(-1, 5))),
    scale_override(5, scale_x_continuous(limits = c(-4, 5)))
  ))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_density_ridges(rel_min_height = 0.01, scale = 2,  col = "white", alpha = .5)+
  stat_pointinterval(.width = .95, size = 1, shape = 1)+
  #xlim(-3,5)+
   scale_fill_colorblind(name = "", guide = "none")+
  theme_minimal()+
  scale_y_discrete(limits=rev)+
  labs(y = "", x = "Model estimate")+
  theme(panel.border  = element_rect(colour = "black",fill = NA))

```



```{r, warning = F}
pai <- proj_samples_sum%>%
  filter(pred == "Age",
         task == "Inference by exclusion")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25,pch = 4, position = position_dodge(width = 1))+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.4, 0.1)+
  scale_color_colorblind(name = "", guide = F)+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

pag <- proj_samples_sum%>%
  filter(pred == "Age",
         task == "Gaze following")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25,pch = 4, position = position_dodge(width = 1))+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.005, 0.02)+
  scale_color_colorblind(name = "", guide = F)+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

ptq <- proj_samples_sum%>%
  filter(pred == "Time spent in research",
         task == "Quantity discrimination")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25,pch = 4, position = position_dodge(width = 1))+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.1, 0.3)+
  scale_color_colorblind(name = "", guide = F)+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )




pti <- proj_samples_sum%>%
  filter(pred == "Time spent in research",
         task == "Inference by exclusion")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25,pch = 4, position = position_dodge(width = 1))+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.2, 1.3)+
  scale_color_colorblind(name = "", guide = F)+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )


ptoc <- proj_samples_sum%>%
  filter(pred == "Time spent outdoors",
         task == "Causal inference")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25,pch = 4)+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.25, 0.1)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

ptoq <- proj_samples_sum%>%
  filter(pred == "Time spent outdoors",
         task == "Quantity discrimination")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), size = .25,pch = 4)+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.2, 0.1)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

ptd <- proj_samples_sum%>%
  filter(pred == "Time spent in research",
         task == "Delay of gratification")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci),size = 0.25, pch = 4)+
  #geom_point(size = 100, pch = 1, col = "black")+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.2, 2.1)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

poq <- proj_samples_sum%>%
  filter(pred == "Observer present",
         task == "Quantity discrimination")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), size = .25,pch = 4)+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-1, 0.3)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

pod <- proj_samples_sum%>%
  filter(pred == "Observer present",
         task == "Delay of gratification")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), size = .25,pch = 4)+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-1, 0.3)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

psd <- proj_samples_sum%>%
  filter(pred == "Sickness severity",
         task == "Delay of gratification")%>%
  ggplot(aes(x = pred, y = mean, col = phase)) +
  geom_hline(yintercept = 0, lty = 3, alpha = .75)+
  geom_pointrange(aes(ymin = lci, ymax = uci), size = .25,pch = 4)+
  labs(y = element_blank(), x = element_blank())+
  theme_void()+
  ylim(-0.3, 0.4)+
  scale_color_manual(name = "", guide = F, values = "#E69F00")+
  theme(panel.background = element_rect(fill = "white",
                                colour = "black",
                                size = 2, linetype = "solid")
        )

```

```{r}
p2_i <- ggdraw() +
  draw_plot(p2) +
  draw_plot(ptq, x = 0.375, y = .39, width = .04, height = .075)+
  draw_plot(pti, x = 0.375, y = .51, width = .04, height = .075)+
  draw_plot(ptd, x = 0.375, y = .27, width = .04, height = .075)+
  draw_plot(pai, x = 0.435, y = .51, width = .04, height = .075)+
  draw_plot(pag, x = 0.435, y = .76, width = .04, height = .075)+
  draw_plot(ptoc, x = 0.68, y = .635, width = .04, height = .075)+
  draw_plot(ptoq, x = 0.68, y = .39, width = .04, height = .075)+
  draw_plot(poq, x = 0.495, y = .39, width = .04, height = .075)+
  draw_plot(pod, x = 0.495, y = .27, width = .04, height = .075)#+
  #draw_plot(psd, x = 0.62, y = .27, width = .04, height = .075)

xp <- ggarrange(
ggarrange( p1, NULL , ncol = 1, heights = c(1,0.02)),
ggarrange(NULL, p2_i , ncol = 1, heights = c(0.06,1)),
widths = c(1,1),
nrow = 1, 
labels = c("A","B"),
vjust = 3,
align = "h")

ggsave(plot=xp,"../writing/paper/figures/ppi3_i6.png", width = 10, height = 6, scale = 1.25, bg = "white")
```

```{r}
xp2 <- ggarrange(
p1,
ggarrange(
  ggarrange(NULL,grouproj, widths = c(0.02,1)),
  otherproj, 
  ncol = 1, 
  heights = c(1,1.5), 
  labels = c("B","C"), 
  align = "v"),
widths = c(1,1.75),
nrow = 1, 
labels = c("A",""))

ggsave(plot=xp2,"../writing/paper/figures/ppi3_i7.png", width = 12, height = 6, scale = 1.25, bg = "white")
```

```{r}
xp3 <- ggarrange(
ggarrange( p1, NULL , ncol = 1, heights = c(1,0.008)),
ggarrange(NULL,p2group, NULL, heights = c(0.075,1,0.253), ncol = 1),
ggarrange(NULL,p2other, heights = c(0.235,1), ncol = 1),
widths = c(1,0.5,0.75),
nrow = 1, 
labels = c("A","B"),
vjust = 3)


ggsave(plot=xp3,"../writing/paper/figures/ppi3_i8.png", width = 10, height = 6, scale = 1.25, bg = "white")
```


```{r}
ggplot(ro,aes(x = fct_reorder(solution_terms,sum), y = size, lty = phase, col = type ))+
  #geom_line(aes(group = task))+
  geom_line(aes(group = phase), alpha = .5, col = "black")+
  geom_point(aes(pch = select), size = 2, stroke = 1)+
  theme_few()+
  facet_grid(task~.)+
  labs(x = "", y = "Rank based on PPI model")+
  scale_color_brewer(palette="Set1", name = "")+
  scale_linetype(name = "")+
  scale_shape_manual(name = "", values =  c(1,4), labels = c("Irrelevant", "Relevant"))+
  scale_y_reverse(breaks = c(15,10,5,1), limits = c(16,0))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.box = "vertical",
        legend.direction = "vertical",
        legend.position = "right", 
        legend.spacing.y = unit(0, 'cm'),
        #legend.spacing.x = unit(0, 'cm')
        )
```

```{r}
ggsave("../writing/paper/figures/ppi3_1.png", width = 8, height = 6, scale = 1.25, bg = "white")
```

```{r}
proj_samples%>%
  filter(factor == "Group")%>%
  ggplot(aes(y = pred,x =value,  fill = phase))+
  geom_vline(xintercept = 0, lty = 2, alpha = .75)+
   stat_slab(height = 2, color = "black", alpha = .75) +
  scale_fill_colorblind()+
  facet_grid(~task, scales = "free_x")+
  theme_minimal_hgrid()
```

```{r}
ggsave("../writing/paper/figures/ppi3_2.png", width = 8, height = 6, scale = 1.25, bg = "white")
```


```{r}
ggplot(ro,aes(y = fct_reorder(solution_terms,-sum), x = size, lty = phase, col = type ))+
  #geom_line(aes(group = task))+
  geom_line(aes(group = phase), alpha = .5, col = "black")+
  geom_point(aes(pch = select), size = 2, stroke = 1)+
  theme_minimal()+
  facet_grid(~task)+
  labs(y = "", x = "Rank based on PPI model")+
  scale_color_brewer(palette="Set1", name = "")+
  scale_linetype(name = "")+
  scale_shape_manual(name = "", values =  c(1,19), labels = c("Irrelevant", "Relevant"))+
  scale_x_continuous(breaks = c(1,5,10,15), limits = c(0,16))+
  theme(#axis.text.x = element_text(angle = 45, hjust = 1),
        legend.box = "vertical",
        legend.direction = "vertical",
        legend.position = "right", 
        legend.spacing.y = unit(0, 'cm'),
        #legend.spacing.x = unit(0, 'cm'),
        panel.border  = element_rect(colour = "black",fill = NA)
        )
```


```{r}
ggsave("../visuals/prediction_1.png", width = 17, height = 4, scale = 1, bg = "white")
```
